version: "3.9"

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    depends_on:
      - db
      - minio
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app

  web:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: picking
      POSTGRES_USER: picking
      POSTGRES_PASSWORD: change_me
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: change_me
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - web

volumes:
  dbdata:
  minio:
