app = "picking-system-backend-qovahglg"
primary_region = "iad"

[build]

[processes]
web = "uvicorn main:app --host 0.0.0.0 --port 8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["web"]

[[http_service.checks]]
interval = "15s"
grace_period = "5s"
method = "get"
path = "/"
protocol = "http"
timeout = "10s"
tls_skip_verify = false

[env]
PORT = "8000"
